### ISSUE TITLE
Generate Flow for a roadnet.json file

### ISSUE THREAD

**Issue by abderraouf2che** [cityflow-project/CityFlow#123]
Hello;
The big issue with the CityFlow project is the lack of documentation and updating the  platform. 

I want to ask is there any way to generate the Flow file from the ready roadnet.json File? 
Thanks

**Comment by only-changer** [comment]
Actually, there is a doc for CityFlow: https://cityflow.readthedocs.io/en/latest/.
For now, we don't have a script for generating flow given roadnet, you can just traverse all roads in your roadnet file, and generate the flow given any two roads as origin and destination. CityFlow has the auto-route generator so that you only need to set the origin road and the destination road instead of the whole route.
