### ISSUE TITLE
Bug report: `Engine.next_step()` segfaults

### ISSUE THREAD

**Issue by ThisIsIsaac** [cityflow-project/CityFlow#50]
`Engine.next_step()` segfaults. 

## Background

I am using roadnet and flow generated with : 

```
python generate_grid_scenario.py 1 1 --roadnetFile 1x1_roadnet.json --flowFile 1x1_flow.json --dir . --tlPlan --numLeftLanes 2 --numRightLanes 1 --numStraightLanes 5
```

A peculiar observation is: there are only cars that go straight. No cars try to make right or left turns even if there are right and left turn lanes.

## Replay files

I have attached two replay files and a roadnet log file. `replay_fine.txt` goes to completion without any error, but `replay_error.txt` which is supposed to run for as many steps as `replay_fine.txt` only runs for 870 steps then it segfaults on `next_step()`.

I first thought it was due the vertical lanes being completely clogged, but this doesn't cause segfault in `replay_fine.txt` even if it is clogged for a longer period of time.

The phase are set correctly, as there is a check for a proper phase index.

[replays.zip](https://github.com/cityflow-project/CityFlow/files/3641075/replays.zip)

**Comment by soodoshll** [comment]
Thank you for submitting the bug report! 

### Turns
> A peculiar observation is: there are only cars that go straight. No cars try to make right or left turns even if there are right and left turn lanes.

As for this problem, the solution is appending "--turn" option in the command like:

` python generate_grid_scenario.py 1 1 --roadnetFile 1x1_roadnet.json --flowFile 1x1_flow.json --dir . --tlPlan --numLeftLanes 2 --numRightLanes 1 --numStraightLanes 5 --turn
`

### Segment Fault
When it comes to the segment fault, I tried but failed to reproduce the bug on my computer. It seems like you are using a new control algorithm instead of the default setting in roadnet config file. It would be a great help if you could offer your code. 

I speculate on what causes the bug and I think it is caused by the lane change mechanism. Does it work properly if you turn off the "laneChange" option in the config file?  I rewrote the "abortLaneChange" function in the lane change module. Please check [issue-50](https://github.com/soodoshll/CityFlow/tree/issue-50)

Does it help? Thank you for you help!

**Comment by ThisIsIsaac** [comment]
@soodoshll Thanks so much for your help!

> As for this problem, the solution is appending "--turn" option in the command

Thanks! got it!

>  It would be a great help if you could offer your code.

unfortunately, it isn't up to me to share the project. I will first try what you have suggested: turning `laneChange` off. Let me get back to you if I see the same problem.

> I rewrote the "abortLaneChange" function in the lane change module. Please check issue-50

what is `issue-50` changing about `abortLaneChange`?

**Comment by soodoshll** [comment]
@ThisIsIsaac, Thank you for your reply 😃 

I find that when the simulation corrupts, there is a vehicle taking lane changing, and meanwhile, about to leave its lane and enter the crossroads (as you can see in the yellow circle)
![TIM截图20190926163657](https://user-images.githubusercontent.com/1694657/65672761-1ededf80-e07c-11e9-88fd-70f87a517e05.png)

Under this circumstances, the simulator will call `abortLaneChange` to abort the lane changing, which is implemented incorrectly. So I rewrote the function, and it now works properly on my computer.

**Comment by ThisIsIsaac** [comment]
I see. So you suspect that incorrectly implemented `abortLaneChange` could have been the cause of segfault?

**Comment by soodoshll** [comment]
Yes. I made some careless omissions.

**Comment by ThisIsIsaac** [comment]
Seems to have fixed the problem! Hasn't segfaulted for tens of millions of steps, where as before I couldn't get to a few hundred thousand steps.
