### ISSUE TITLE
Does cityflow support vehicles with different size  

### ISSUE THREAD

**Issue by sachin-iitd** [cityflow-project/CityFlow#76]
If I simulate a bus having width of 2 lanes, a car (as usual with width of 1 lane) and a motorbike with a high speed, can cityflow support such difference in vehicles' sizes/speeds. 
If yes, is there a way to get back the type (size) of vehicle back from simulator.

**Comment by only-changer** [comment]
Cityflow does support different size and speed. You can take a look at examples/flow.json, and you can see that a vehicle has several properties such as length, width, and max speed. 
 To get back the type (size) of vehicles back from the simulator, I don't think it would be a problem because all vehicles are defined by you in flow.json, and the simulator will not change it. If you insist, you can find it in the replay file: replay.txt.

**Comment by sachin-iitd** [comment]
So, if I get want to check the size of a vehicle named flow_30_0, can I directly refer to the corresponding 31st (or 30th) vehicle in the flow.json (provided start/end times are same).

I want to get identify the vehicle during simulation, either by using size or speed or type etc. Replay might help after simulation ends. Can you suggest a way to have that done during the simulation.

Thanks

**Comment by only-changer** [comment]
Yes, you can directly refer to the corresponding 31st (or 30th) flow in the flow.json;
Every vehicle has a unique name, such as flow_30_0, so I suggest you use the vehicle name to identify.
By the way, vehicles are named by their flow type(what you define in the flow.json) and their order. For example, flow_30_10 means the 11th vehicle of the 31st flow type.
