### ISSUE TITLE
when "eng.next_step()", came error: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by chuckbassx** [cityflow-project/CityFlow#97]
I‘m running my codes on CityFlow，when it ran to "eng.next_step()", the codes stopped with the error "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"

**Comment by only-changer** [comment]
That error means you have triggered some mistake in the underlying C++ code of Cityflow. It may because you have used an incorrect roadnet.  Please double-check your roadnet. Or you can clone this repo and open it as a C++ project (such as by Clion). Running "tools/debug/simple_run.cpp" will show your the detailed error information.
